Loading training set...
/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(

Num images:  4214
Image shape: [3, 512, 512]
Label shape: [0]

Constructing networks...
Traceback (most recent call last):
  File "/zhome/51/7/168082/Desktop/Tester/stylegan3-main/train.py", line 286, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/zhome/51/7/168082/Desktop/Tester/stylegan3-main/train.py", line 281, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/zhome/51/7/168082/Desktop/Tester/stylegan3-main/train.py", line 96, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "/zhome/51/7/168082/Desktop/Tester/stylegan3-main/train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/zhome/51/7/168082/Desktop/Tester/stylegan3-main/training/training_loop.py", line 152, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/zhome/51/7/168082/Desktop/Tester/test-env1/lib/python3.9/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
